#!/usr/bin/env swift

import Foundation

// MARK: - Models

struct IconCategory {
    let name: String
    let icons: [String]
}

// MARK: - Helpers

func toCamelCase(_ string: String) -> String {
    guard !string.isEmpty else { return string }

    // Handle special cases
    let specialCases = ["3D": "threeD", "360": "threeSixty"]
    if let specialCase = specialCases[string] {
        return specialCase
    }

    // Convert "AddCircleFill" -> "addCircleFill"
    let firstChar = string.prefix(1).lowercased()
    let rest = string.dropFirst()
    return firstChar + rest
}

func isReservedKeyword(_ word: String) -> Bool {
    let keywords = ["class", "do", "import"]
    return keywords.contains(word.lowercased())
}

func sanitizeName(_ name: String) -> String {
    if isReservedKeyword(name) {
        return "`\(name)`"
    }
    return name
}

// MARK: - File System Operations

func findIconCategories(at path: String) -> [IconCategory] {
    let fileManager = FileManager.default
    var categories: [IconCategory] = []

    guard let enumerator = fileManager.enumerator(
        at: URL(fileURLWithPath: path),
        includingPropertiesForKeys: [.isDirectoryKey],
        options: [.skipsHiddenFiles]
    ) else {
        print("Error: Cannot enumerate directory at \(path)")
        return []
    }

    var categoryDict: [String: [String]] = [:]

    for case let fileURL as URL in enumerator {
        guard let resourceValues = try? fileURL.resourceValues(forKeys: [.isDirectoryKey]),
              let isDirectory = resourceValues.isDirectory,
              isDirectory,
              fileURL.lastPathComponent.hasSuffix(".imageset") else {
            continue
        }

        // Get category name (parent folder)
        let categoryName = fileURL.deletingLastPathComponent().lastPathComponent

        // Skip if it's the root or Contents.json
        guard categoryName != "Iconography.xcassets" && categoryName != "Contents.json" else {
            continue
        }

        // Get icon name (without .imageset)
        let iconName = fileURL.lastPathComponent.replacingOccurrences(of: ".imageset", with: "")

        if categoryDict[categoryName] == nil {
            categoryDict[categoryName] = []
        }
        categoryDict[categoryName]?.append(iconName)
    }

    // Convert to IconCategory array and sort
    for (categoryName, icons) in categoryDict {
        let sortedIcons = icons.sorted()
        categories.append(IconCategory(name: categoryName, icons: sortedIcons))
    }

    return categories.sorted { $0.name < $1.name }
}

// MARK: - Code Generation

func generateCategoryStruct(category: IconCategory) -> String {
    var output = "  // swiftlint:disable all\n"
    output += "  public struct \(category.name): Sendable {\n"

    // Generate properties for each icon
    for icon in category.icons {
        let propertyName = sanitizeName(toCamelCase(icon))
        output += "    public let \(propertyName) = ImageAsset(name: \"\(category.name)/\(icon)\")\n"
    }

    output += "\n"
    output += "    public static let shared: Self = .init()\n"
    output += "\n"
    output += "    private init() { }\n"
    output += "  }\n"

    return output
}

func generateIconographyFile(categories: [IconCategory]) -> String {
    var output = "// swiftlint:disable all\n"
    output += "// Generated using generate-iconography-codebase.swift\n"
    output += "// DO NOT EDIT - This file is automatically generated\n\n"
    output += "// MARK: - Iconography\n\n"
    output += "// swiftlint:disable all\n"
    output += "public struct Iconography {\n"

    // Generate category structs
    for category in categories {
        output += generateCategoryStruct(category: category)
        output += "\n"
    }

    output += "}\n"

    return output
}

// MARK: - Main

func main() {
    print("🚀 Starting Iconography generation...")

    let currentDirectory = FileManager.default.currentDirectoryPath
    let iconographyPath = "\(currentDirectory)/Resources/Sources/Core/Assets/Iconography.xcassets"
    let outputPath = "\(currentDirectory)/Resources/Sources/Core/Iconography"
    let outputFile = "\(outputPath)/Iconography+Generated.swift"

    // Check if iconography directory exists
    guard FileManager.default.fileExists(atPath: iconographyPath) else {
        print("❌ Error: Iconography.xcassets not found at \(iconographyPath)")
        exit(1)
    }

    // Find all icon categories
    print("📂 Scanning for icon categories...")
    let categories = findIconCategories(at: iconographyPath)

    guard !categories.isEmpty else {
        print("❌ Error: No icon categories found")
        exit(1)
    }

    print("✅ Found \(categories.count) categories:")
    for category in categories {
        print("  - \(category.name): \(category.icons.count) icons")
    }

    // Generate code
    print("\n💻 Generating Swift code...")
    let generatedCode = generateIconographyFile(categories: categories)

    // Create output directory if needed
    do {
        try FileManager.default.createDirectory(
            atPath: outputPath,
            withIntermediateDirectories: true,
            attributes: nil
        )
    } catch {
        print("❌ Error creating output directory: \(error)")
        exit(1)
    }

    // Write to file
    do {
        try generatedCode.write(toFile: outputFile, atomically: true, encoding: .utf8)
        print("✅ Successfully generated: \(outputFile)")
        print("\n🎉 Done!")
    } catch {
        print("❌ Error writing file: \(error)")
        exit(1)
    }
}

main()
