configurations:
  - sources:
      include:
        - Sources/
      exclude:
        - Sources/Testing/
        - Sources/SnapshotTesting/
    templates:
      - ../../.tools/.sourcery/template/
    output: Sources/Testing/Generated/Sourcery.generated.swift
    args:
      autoMockableImports: [Combine]
      autoMockableTestableImports: [__COMPONENT_NAME___Component]
